/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'qurt' at '17-5-25 下午8:41' with Gradle 2.4
 *
 * @author qurt, @date 17-5-25 下午8:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
